### ISSUE TITLE
participles

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/morpheus#50]
I just noticed that the morphological id of participles gives their number, gender, and case, but does not give the equally crucial information of tense and voice.  This is a major issue.

**Comment by balmas** [comment]
this will be addressed in the next incremental release via alpheios-project/alpheios-core#55
(fix made, pending testing and release)

**Comment by vgorman1** [comment]
Excellent.  My heart skipped a beat there.

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/
