### ISSUE TITLE
βραχέως 

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/morpheus#51]
βραχέως  is correctly identified as an adverb made from the adjective βραχύς, short, but there is no link to the LSJ entry.

**Comment by balmas** [comment]
hmm. this one I can't reproduce.  I get the LSJ entry

![Screenshot from 2020-12-24 11-18-20](https://user-images.githubusercontent.com/644870/103098712-cc230900-45d9-11eb-876b-ecae6bc588c2.png)

**Comment by vgorman1** [comment]
Maybe it was just being very slow to load up at the time I tried it??? I can load it now, too.

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by balmas** [comment]
>Maybe it was just being very slow to load up at the time I tried it??? 

That could be, although it doesn't make me happy :-(
